version: "3.8"

services:
  backend:
    build: .
    ports:
      - "9999:8895"
    env_file:
      - .env
    environment:
      - DB_HOST=db

      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
